// General hp/mana/etc colors
#define XQUI_HP_COL							0xb70707
#define XQUI_MANA_COL						0x1111d6
#define XQUI_END_COL						0x888888
#define XQUI_NRG_COL						0x11d611
#define XQUI_TARGET_COL						0xb80707


// Big bars
#define XQUI_BIGBARS_BAR_WIDTH				800
#define XQUI_BIGBARS_BAR_HEIGHT				28
#define XQUI_BIGBARS_BAR_ALPHA				0.7
#define XQUI_BIGBARS_MARGIN					1
#define XQUI_BIGBARS_TEXT_Y_MARGIN			8

#define XQUI_BIGBARS_TEXT_COLOR				0xffffff
#define XQUI_BIGBARS_TEXT_ALPHA				0.5
#define XQUI_BIGBARS_TEXT_SIZE				2

#define XQUI_BIGBARS_HP_BAR_BGCOL			0x820303
#define XQUI_BIGBARS_HP_BAR_GRADCOL			XQUI_HP_COL
#define XQUI_BIGBARS_HP_BAR_GRADMIRROR		1

#define XQUI_BIGBARS_MANA_BAR_BGCOL			0x0d0da5
#define XQUI_BIGBARS_MANA_BAR_GRADCOL		XQUI_MANA_COL
#define XQUI_BIGBARS_MANA_BAR_GRADMIRROR	1

#define XQUI_BIGBARS_END_BAR_BGCOL			0x333333
#define XQUI_BIGBARS_END_BAR_GRADCOL		XQUI_END_COL
#define XQUI_BIGBARS_END_BAR_GRADMIRROR		1

#define XQUI_BIGBARS_NRG_BAR_BGCOL			0x0da40d
#define XQUI_BIGBARS_NRG_BAR_GRADCOL		XQUI_NRG_COL
#define XQUI_BIGBARS_NRG_BAR_GRADMIRROR		1


// Small bars
#define XQUI_SMALLBARS_BAR_WIDTH			200
#define XQUI_SMALLBARS_BAR_HEIGHT			10
#define XQUI_SMALLBARS_BAR_BRDWIDTH			1
#define XQUI_SMALLBARS_MARGIN				2
#define XQUI_SMALLBARS_HP_COL				XQUI_HP_COL
#define XQUI_SMALLBARS_MANA_COL				XQUI_MANA_COL
#define XQUI_SMALLBARS_END_COL				XQUI_END_COL
#define XQUI_SMALLBARS_NRG_COL				XQUI_NRG_COL


// Big target
#define XQUI_BIGTARGET_MARGIN				1
#define XQUI_BIGTARGET_BAR_WIDTH			800
#define XQUI_BIGTARGET_BAR_HEIGHT			28
#define XQUI_BIGTARGET_BAR_BGCOL			0x820303
#define XQUI_BIGTARGET_BAR_GRADCOL			XQUI_TARGET_COL
#define XQUI_BIGTARGET_BAR_GRADMIRROR		1
#define XQUI_BIGTARGET_BAR_ALPHA			0.7
#define XQUI_BIGTARGET_TEXT_SIZE			2


// Small target
#define XQUI_SMALLTARGET_MARGIN				2
#define XQUI_SMALLTARGET_BAR_WIDTH			200
#define XQUI_SMALLTARGET_BAR_HEIGHT			10
#define XQUI_SMALLTARGET_BAR_BRDWIDTH		1
#define XQUI_SMALLTARGET_BGCOL				0xb80707


// XP bar
#define XQUI_XP_BAR_WIDTH					800
#define XQUI_XP_BAR_HEIGHT					30
#define XQUI_XP_BAR_MARGIN					1
#define XQUI_XP_BAR_BGCOL					0x987f09
#define XQUI_XP_BAR_GRADCOL					0xc6a50c
#define XQUI_XP_BAR_GRADMIRROR				1
#define XQUI_XP_BAR_ALPHA					0.7
#define XQUI_XP_FASTBAR_HEIGHT				1
#define XQUI_XP_TEXT_SIZE					2


// Casting bar
#define XQUI_CASTING_BAR_WIDTH				100
#define XQUI_CASTING_BAR_HEIGHT				20
#define XQUI_CASTING_BAR_FILLEDCOLOR		0xff99ff
#define XQUI_CASTING_BAR_EMPTYCOLOR			0x99ff99

// inventory window
#define XQUI_INV_WIN_WIDTH					500
#define XQUI_INV_WIN_HEIGHT					600
#define XQUI_INV_OBJSLOTS_X					150
#define XQUI_INV_OBJSLOTS_Y					50
#define XQUI_INV_OBJSLOT_SEPARATION			2

// skills window
#define XQUI_SKILLS_WIN_WIDTH				400
#define XQUI_SKILLS_WIN_HEIGHT				600


// spell book
#define XQUI_SPELL_BOOK_WIDTH				800
#define XQUI_SPELL_BOOK_HEIGHT				558


// Book
#define XQUI_BOOK_WIN_WIDTH					400
#define XQUI_BOOK_WIN_HEIGHT				500


// Loot
#define XQUI_LOOT_COLUMNS					5
#define XQUI_LOOT_ROWS						9
#define XQUI_LOOT_DIST						2


// Merchant
#define XQUI_MERCHANT_WIN_WIDTH				400
#define XQUI_MERCHANT_WIN_HEIGHT			950
